### PR TITLE
Added docker-compose.yml + readme

### PR DESCRIPTION
**Pull request by JanC**

### CODE REVIEW

**Comment by flyinactor91** [comment]
The readme does need to be expanded (and be useful) yes, but having a MongoDB backend available is not necessary for working on the API. The avwx_api.cache.Cache class handles the lack of a database connection and forces the API to go through the normal process of fetching and parsing the report. This is in fact preferable to caching during development.

**Comment by JanC** [comment]
ok I see, I’ll update the development readme steps to reflect this

**Comment by JanC** [comment]
I've updated the readme

**Comment by flyinactor91** [comment]
Merged but some fixes will need to be made before pushing to server

**Comment by JanC** [comment]
> Merged 

You mean _closed_?

**Comment by flyinactor91** [comment]
You're right. Posted on the wrong one.

**Comment by JanC** [comment]
something went wrong during rebase :) I'm closing this

**Pull request closed without merging**
